# Generated by Django 5.2.10 on 2026-01-18 06:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa firmy')),
                ('nip', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='NIP musi składać się z 10 cyfr', regex='^\\d{10}$')], verbose_name='NIP')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Branża')),
                ('website', models.URLField(blank=True, verbose_name='Strona WWW')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Ulica')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('country', models.CharField(default='Polska', max_length=100, verbose_name='Kraj')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Telefon komórkowy')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Stanowisko')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Klient'), ('churned', 'Utracony')], default='lead', max_length=20, verbose_name='Status')),
                ('tags', models.CharField(blank=True, help_text='Oddziel przecinkami', max_length=200, verbose_name='Tagi')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Ulica')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Kraj')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniego kontaktu')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.company', verbose_name='Firma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
