# Generated by Django 5.2.10 on 2026-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='erp_customer_code',
            field=models.CharField(blank=True, help_text='Kod klienta w systemie ERP (np. Comarch XL)', max_length=50, verbose_name='Kod kontrahenta w ERP'),
        ),
    ]
