# Generated by Django 5.2.10 on 2026-01-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon'), ('meeting', 'Spotkanie'), ('note', 'Notatka'), ('call', 'Połączenie'), ('other', 'Inne')], max_length=20, verbose_name='Typ interakcji')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('description', models.TextField(verbose_name='Opis')),
                ('interaction_date', models.DateTimeField(verbose_name='Data interakcji')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Dla spotkań i połączeń', null=True, verbose_name='Czas trwania (minuty)')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='interactions/%Y/%m/', verbose_name='Załączniki')),
                ('is_important', models.BooleanField(default=False, verbose_name='Oznacz jako ważne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.company', verbose_name='Firma')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact', verbose_name='Kontakt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Interakcja',
                'verbose_name_plural': 'Interakcje',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
