# Generated by Django 5.2.10 on 2026-01-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_company_erp_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPCustomerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, help_text='Kod kontrahenta w ERP', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('nip', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Limit kredytowy', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo (dodatnie = nasz dług, ujemne = ich dług)', max_digits=12)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(help_text='Powiązana firma w CRM', on_delete=django.db.models.deletion.CASCADE, related_name='erp_cache', to='contacts.company')),
            ],
            options={
                'verbose_name': 'Cache kontrahenta ERP',
                'verbose_name_plural': 'Cache kontrahentów ERP',
            },
        ),
        migrations.CreateModel(
            name='ERPDeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, help_text='ID dokumentu w ERP', max_length=100, unique=True)),
                ('document_number', models.CharField(max_length=100)),
                ('document_type', models.CharField(default='WZ', max_length=10)),
                ('document_date', models.DateField()),
                ('related_invoice', models.CharField(blank=True, help_text='Powiązana faktura', max_length=100)),
                ('related_order', models.CharField(blank=True, help_text='Powiązane zamówienie', max_length=100)),
                ('raw_data', models.JSONField(blank=True, help_text='Pełne dane z API ERP', null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Firma której dotyczy dokument', on_delete=django.db.models.deletion.CASCADE, related_name='erp_delivery_notes', to='contacts.company')),
            ],
            options={
                'verbose_name': 'Dokument WZ ERP',
                'verbose_name_plural': 'Dokumenty WZ ERP',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='ERPInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, help_text='ID faktury w ERP', max_length=100, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(choices=[('FS', 'Faktura sprzedaży'), ('FKOR', 'Faktura korygująca'), ('FP', 'Faktura pro-forma'), ('FV', 'Faktura VAT')], default='FS', max_length=10)),
                ('invoice_date', models.DateField()),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('payment_status', models.CharField(choices=[('paid', 'Opłacona'), ('unpaid', 'Nieopłacona'), ('overdue', 'Zaległa'), ('partial', 'Częściowo opłacona')], default='unpaid', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_data', models.JSONField(blank=True, help_text='Pełne dane z API ERP', null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Firma której dotyczy faktura', on_delete=django.db.models.deletion.CASCADE, related_name='erp_invoices', to='contacts.company')),
            ],
            options={
                'verbose_name': 'Faktura ERP',
                'verbose_name_plural': 'Faktury ERP',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ERPOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, help_text='ID zamówienia w ERP', max_length=100, unique=True)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Projekt'), ('confirmed', 'Potwierdzony'), ('in_progress', 'W realizacji'), ('completed', 'Zrealizowany'), ('cancelled', 'Anulowany')], default='draft', max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Pełne dane z API ERP (backup)', null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Firma której dotyczy zamówienie', on_delete=django.db.models.deletion.CASCADE, related_name='erp_orders', to='contacts.company')),
            ],
            options={
                'verbose_name': 'Zamówienie ERP',
                'verbose_name_plural': 'Zamówienia ERP',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('orders', 'Zamówienia'), ('invoices', 'Faktury'), ('delivery_notes', 'Dokumenty WZ'), ('payments', 'Płatności'), ('summary', 'Podsumowanie'), ('full', 'Pełna synchronizacja')], help_text='Typ synchronizacji', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Sukces'), ('error', 'Błąd'), ('partial', 'Częściowy')], default='success', max_length=20)),
                ('records_synced', models.IntegerField(default=0, help_text='Liczba zsynchronizowanych rekordów')),
                ('error_message', models.TextField(blank=True, help_text='Komunikat błędu (jeśli wystąpił)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Czas trwania synchronizacji w sekundach', null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Firma której dotyczy synchronizacja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_sync_logs', to='contacts.company')),
            ],
            options={
                'verbose_name': 'Log synchronizacji ERP',
                'verbose_name_plural': 'Logi synchronizacji ERP',
                'ordering': ['-started_at'],
            },
        ),
    ]
