# Generated by Django 5.2.10 on 2026-01-18 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('todo', 'Do zrobienia'), ('in_progress', 'W trakcie'), ('done', 'Wykonane'), ('cancelled', 'Anulowane')], default='todo', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka'), ('urgent', 'Pilne')], default='medium', max_length=20, verbose_name='Priorytet')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Termin wykonania')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Data przypomnienia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wykonania')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.company', verbose_name='Firma')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.contact', verbose_name='Kontakt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
    ]
