# Generated by Django 5.2.10 on 2026-01-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Np. "Wdrożenie CRM dla Acme Corp"', max_length=200, verbose_name='Nazwa szansy')),
                ('description', models.TextField(blank=True, help_text='Szczegóły szansy sprzedażowej', verbose_name='Opis')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Przewidywana wartość transakcji', max_digits=12, verbose_name='Wartość (PLN)')),
                ('probability', models.IntegerField(default=50, help_text='Szansa na wygraną (0-100%)', verbose_name='Prawdopodobieństwo (%)')),
                ('stage', models.CharField(choices=[('qualification', 'Kwalifikacja'), ('proposal', 'Propozycja'), ('negotiation', 'Negocjacje'), ('closed_won', 'Wygrana'), ('closed_lost', 'Przegrana')], default='qualification', max_length=20, verbose_name='Etap')),
                ('expected_close_date', models.DateField(help_text='Kiedy spodziewamy się decyzji?', verbose_name='Przewidywana data zamknięcia')),
                ('actual_close_date', models.DateField(blank=True, help_text='Kiedy faktycznie zamknięto (won/lost)', null=True, verbose_name='Rzeczywista data zamknięcia')),
                ('lost_reason', models.CharField(blank=True, choices=[('price', 'Za drogo'), ('competitor', 'Wybrał konkurencję'), ('no_budget', 'Brak budżetu'), ('timing', 'Zły timing'), ('no_decision', 'Nie podjęto decyzji'), ('other', 'Inny powód')], max_length=20, null=True, verbose_name='Powód przegranej')),
                ('lost_reason_details', models.TextField(blank=True, help_text='Dodatkowe informacje dlaczego przegraliśmy', verbose_name='Szczegóły przegranej')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='contacts.company', verbose_name='Firma')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='contacts.contact', verbose_name='Kontakt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Szansa sprzedaży',
                'verbose_name_plural': 'Szanse sprzedaży',
                'ordering': ['-expected_close_date'],
            },
        ),
    ]
